// Generated by CoffeeScript 1.6.3
#import "../../tuneup_js/tuneup.js"
(function() {
  test("Show 'Authorization Required' alert when user is not logged in.", function(target, app) {
    var window;
    target.delay(2);
    window = app.mainWindow();
    window.navigationBars()[0].rightButton().tap();
    target.frontMostApp().activityView().scrollViews()[0].buttons()["Hatena Bookmark"].tap();
    UIATarget.onAlert = function(alert) {
      assertEquals(alert.name(), 'Authorization Required');
      return true;
    };
    return target.delay(3);
  });
}).call(this);
