// Generated by CoffeeScript 1.6.3
#import "../../tuneup_js/tuneup.js"
(function() {
  test("Dismiss 'HTBHatenaBookmarkViewController' when tap cancel button.", function(target, app) {
    var window;
    target.delay(2);
    window = app.mainWindow();
    window.navigationBars()[0].rightButton().tap();
    target.frontMostApp().activityView().scrollViews()[0].buttons()["Hatena Bookmark"].tap();
    UIATarget.onAlert = function(alert) {
      target.delay(1);
      alert.cancelButton().tap();
      target.delay(1);
      assertEquals(window.navigationBars().length, 1);
      return true;
    };
    return target.delay(3);
  });

}).call(this);
